Updating contributor policy
aspirepress/.github pull request #12
Opened 2024-11-10 11:45 UTC by asirota

# Pull Request

## What changed?

This change is in relation to issue #11 

The sentences serve to confuse and potentially scare any contributors. Removing these 2 sentences will lighten the tone of the PR template.

## Why did it change?

Suggestion from the AspireUpdate team...

## Did you fix any specific issues?

#11 

## CERTIFICATION

By opening this pull request, I do agree to abide by the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the ersion in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.

Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree that this code may be licensed under any license deemed appropriate by AspirePress, including but not limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my rights or my copyright to this code.

2024-11-10 11:45 UTC, asirota commented
I'll add @costdev when he joins as a contributor to the AP project on GitHub.

2024-11-10 12:15 UTC, namithj approved these changes

2024-11-10 13:02 UTC, costdev requested changes

2024-11-10 13:26 UTC, asirota commented on CONTRIBUTING.md
> +When creating a pull requests or committing changes to any AspirePress repository, contributors certify that their contributions are their own, are original and do not violate the intellectual proper
@costdev can you please go the issue #11 and state your concern here and I'll respond there.

2024-11-10 14:48 UTC, chuckadams commented
Less boilerplate good, but maybe we should at keep a single sentence like "By submitting this PR I acknowledge to abide by the terms of the Code of Conduct and the Contributor Guidelines." (with appropriate links).  Just a HR separating it, no need for a big CERTIFICATION header even.

2024-11-10 20:48 UTC, asirota commented
Fixed the typos for the hyperlinks to code of conduct and contributing files.

2024-11-11 22:57 UTC, toderash approved these changes

2024-11-11 22:57 UTC, merged